- name: Create a VM from a template
  community.general.xenserver_guest:
    name: "{{ vm_name }}"
    state: poweredon
    template: "{{ vm_template }}"
    disks:
    - size_gb: "{{ vm_storage_size }}"
      sr: "{{ Local Storage }}"
    hardware:
      num_cpus: "{{ vm_core_count }}"
      memory_mb: "{{ vm_memory }}"
    cdrom:
      type: iso
      iso_name: "{{ vm_installer_iso }}"
    networks:
    - name: "{{ vm_network }}"
    wait_for_ip_address: true
  delegate_to: localhost
  register: deploy